add more step

diff --git a/.github/workflows/update-repos.yaml b/.github/workflows/update-repos.yaml
--- a/.github/workflows/update-repos.yaml
+++ b/.github/workflows/update-repos.yaml
@@ -1,6 +1,5 @@
 name: Update Repositories
-
-run-name: Update directories action started by ${{github.actor}}
+run-name: Update directories action started by ${{ github.actor }}
 
 on:
   push:
@@ -12,13 +11,38 @@ defaults:
     shell: bash --noprofile --norc -exo pipefail {0}
 
 jobs:
-  update:
+  get-repos:
     runs-on: ubuntu-latest
-
+    outputs:
+      repos: ${{ steps.get-repos.outputs.repos }}
     steps:
       - name: Checkout actions repository
         uses: actions/checkout@v2
-      - name: set up ssh key
+
+      - name: Set up SSH key
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+
+      - name: Get template-project repositories
+        id: get-repos
+        run: |
+          REPOSITORIES=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" https://api.github.com/user/repos | jq -r '.[] | select(.name | contains("template-project")) | .ssh_url' | tr '\n' ' ')
+          echo "repos=$REPOSITORIES" >> $GITHUB_ENV
+
+  update-repos:
+    needs: get-repos
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        repo: ${{ fromJson(needs.get-repos.outputs.repos) }}
+    steps:
+      - name: Checkout actions repository
+        uses: actions/checkout@v2
+
+      - name: Set up SSH key
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
@@ -30,61 +54,50 @@ jobs:
           git config --global user.email "actions@github.com"
           git config --global user.name "bot"
 
-      - name: Get template-project repositories
-        id: get-repos
+      - name: Process repository
+        id: process-repo
         run: |
-          REPOSITORIES=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" https://api.github.com/user/repos | jq -r '.[] | select(.name | contains("template-project")) | .ssh_url')
-          echo "repos=$REPOSITORIES" >> $GITHUB_OUTPUT
-
-      - name: Get template-project repositories
-        id: teste
-        run: echo ${{ steps.get-repos.outputs.repos }}
-
-      - name: Process each repository
-        id: process-repos
-        run: |
+          repo=${{ matrix.repo }}
           ERRORS=""
-          for repo in ${{ steps.get-repos.outputs.repos }}; do
-            echo "Processing repository $repo"
-            (
-              set -e
-              trap 'ERROR="Erro ao processar o repositório $repo"; ERRORS="$ERRORS\n$ERROR"; exit 1' ERR
+          echo "Processing repository $repo"
+          (
+            set -e
+            trap 'ERROR="Erro ao processar o repositório $repo"; ERRORS="$ERRORS\n$ERROR"; exit 1' ERR
 
-              echo "Cloning repository $repo"
-              git clone $repo cloned -b develop
+            echo "Cloning repository $repo"
+            git clone $repo cloned -b develop
 
-              if [ ! -d "cloned/.github/workflows" ]; then
-                echo "Creating .github/workflows directory in cloned repository"
-                mkdir -p cloned/.github/workflows
-              fi
+            if [ ! -d "cloned/.github/workflows" ]; then
+              echo "Creating .github/workflows directory in cloned repository"
+              mkdir -p cloned/.github/workflows
+            fi
 
-              echo "Copying workflows to cloned repository"
-              cp -r .github/actions/* cloned/.github/workflows
+            echo "Copying workflows to cloned repository"
+            cp -r .github/actions/* cloned/.github/workflows
 
-              cd cloned
-              git add .
-              git status
-              if ! git diff --cached --quiet --exit-code; then
-                echo "Committing and pushing changes to $repo"
-                git commit -m "build(github): bot update repository workflows"
-                git push
-                git pull
-                git rebase origin/main
-                git push --force-with-lease
-              else
-                echo "No changes detected by git diff --cached"
-              fi
-              cd ..
-              rm -rf cloned
-            ) || {
-              echo "Falha ao atualizar o repositório $repo"
-              ERRORS="$ERRORS\nFalha ao atualizar o repositório $repo"
-              continue
-            }
-          done
-          echo "errors=$ERRORS" >> $GITHUB_OUTPUT
+            cd cloned
+            git add .
+            git status
+            if ! git diff --cached --quiet --exit-code; then
+              echo "Committing and pushing changes to $repo"
+              git commit -m "build(github): bot update repository workflows"
+              git push
+              git pull
+              git rebase origin/main
+              git push --force-with-lease
+            else
+              echo "No changes detected by git diff --cached"
+            fi
+            cd ..
+            rm -rf cloned
+          ) || {
+            echo "Falha ao atualizar o repositório $repo"
+            ERRORS="$ERRORS\nFalha ao atualizar o repositório $repo"
+            echo "$ERRORS" >> $GITHUB_ENV
+            continue
+          }
 
       - name: Display errors
-        if: steps.process-repos.outputs.errors != ''
+        if: ${{ env.ERRORS }}
         run: |
-          echo -e "Os seguintes erros ocorreram durante o processamento dos repositórios:\n${{ steps.process-repos.outputs.errors }}"
+          echo -e "Os seguintes erros ocorreram durante o processamento dos repositórios:\n${{ env.ERRORS }}"
